name: Deploy React Frontend to Staging

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  deploy:
    name: Deploy Frontend (React → S3 + CloudFront via CDK)
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::383033712866:role/GitHubDeployCdkRole
          aws-region: ap-southeast-1

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Download .env.staging from backend
        uses: actions/download-artifact@v4
        with:
          name: frontend-env
          path: ./

      - name: Show environment
        run: cat .env.staging

      - name: Build React App
        run: npm run build

      - name: Install CDK
        run: npm install -g aws-cdk

      - name: Deploy FrontendStack (upload dist/)
        run: cdk deploy FrontendStack --require-approval never
