name: Deploy Backend to Staging

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    name: Deploy Backend (CDK)
    runs-on: ubuntu-latest

    environment: staging

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::383033712866:role/GitHubDeployCdkRole
          aws-region: ap-southeast-1

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install CDK
        run: npm install -g aws-cdk

      - name: Build Lambda
        run: npm run build:lambda

      - name: CDK Bootstrap (if needed)
        run: cdk bootstrap aws://383033712866/ap-southeast-1

      - name: Deploy backend stacks
        run: cdk deploy DynamoDBStack LambdaStack WebSocketStack --require-approval never
